

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import SessionProvider from "@/components/SessionProvider";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import NavbarWrapper from "@/components/NavbarWrapper";
import FooterWrapper from "@/components/FooterWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();

  // eslint-disable-next-line react-hooks/rules-of-hooks


  console.log("CURRENT SESSION:", session); //test
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider session={session}>

          {/* here where i should put static elements like navbar */}
        <NavbarWrapper session={session}/>
          <main>
            {children}
          </main>
        </SessionProvider>
        <FooterWrapper />
      </body>
    </html>
  );
}

